on: push
name: ğŸš€ Publish Website over SFTP
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@main
      with:
        fetch-depth: 2
    #- name: ğŸ—ï¸ Checkout LFS items
    #  run: |
    #    git lfs pull
    #    git status
    - name: ğŸ“‚ Sync files
      uses: Automattic/FTP-Deploy-Action@3.0.1
      with:
        ftp-server: sftp://sftp.wp.com/htdocs/
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        known-hosts: "sftp.wp.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB\
          AAABAQDwfT/YEhOKO2Z0+XrjRqUS5Q2Ali6AlhOhZtzlIfMOvm03Sype\
          DJH70tlUHasS+nm0SnZ01fOiEeAXa91ZhMihIYUT3nTGuiA2J3uVYsyS\
          CJefvhWc0kg1FbEus3V3cVmx4e3XctdkzLbOgPNngypZocbP+8yCpbx6\
          Kb9lihmgTjgGn2QzbK1enRSzsN/CbjVhej9jwukbrWqdCrQsKAsoZ2p6\
          YCtcKbHS+Yy4RwcO9PxZUBkeMXUrejms027bRcdVfwf55hWSD9xYEHpE\
          HupkSL4ofWs3UKeRGz+jCCzl7Nu0S6VSwK4Zzll0auHI0Hwh8WKTJbSn\
          1gxCdF93/rmP"
    - name: ğŸ¤– Install expect
      run: apt-get install expect
    - name: ğŸ™ˆ Update secrets - wp-content/plugins/documents-from-git/includes/config.json
      run: sed -i '' 's/#{PAT_CHRISTOPHERSCHUBERT}#/${{ secrets.PAT_CHRISTOPHERSCHUBERT }}/g' wp-content/plugins/documents-from-git/includes/config.json
    - name: ğŸš¢ Ship it via SFTP!
      run: |
        spawn sftp ${{ secrets.FTP_USER }}@sftp.wp.com
        expect "password:"
        send "${{ secrets.FTP_PASSWORD }}\n"
        expect "sftp>"
        send "put wp-content/plugins/documents-from-git/includes/config.json wp-content/plugins/documents-from-git/includes/config.json\n"
        expect "sftp>"
        send "exit\n"
        interact

